import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const Jquery = dynamic(() => import("./Jquery"), { ssr: false });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://www.youtube.com/iframe_api" defer></script>
      </head>
      <body>
        {children}
        <Jquery />
      </body>
    </html>
  );
}
